export const THEMES = [
  {
    id: "dark",
    label: "다크",
    isDark: true,
    bg: "#1a1f2e",
    sidebar: "#141824",
    card: "rgba(255,255,255,0.04)",
    text: "#e2e8f0",
    accent: "#f59e0b",
    border: "rgba(255,255,255,0.1)",
    subtext: "#94a3b8",
  },
  {
    id: "dark-gray",
    label: "다크 그레이",
    isDark: true,
    bg: "#1e2028",
    sidebar: "#17191f",
    card: "rgba(255,255,255,0.04)",
    text: "#e2e8f0",
    accent: "#f59e0b",
    border: "rgba(255,255,255,0.1)",
    subtext: "#94a3b8",
  },
  {
    id: "light-white",
    label: "화이트",
    isDark: false,
    bg: "#f8f9fa",
    sidebar: "#ffffff",
    card: "#ffffff",
    text: "#1a1a2e",
    accent: "#7c3aed",
    border: "#e5e7eb",
    subtext: "#6b7280",
  },
  {
    id: "light-pink",
    label: "핑크",
    isDark: false,
    bg: "#fff0f5",
    sidebar: "#fff5f8",
    card: "#ffffff",
    text: "#2d1b2e",
    accent: "#ec4899",
    border: "#fce7f3",
    subtext: "#9d4f6e",
  },
  {
    id: "light-yellow",
    label: "옐로우",
    isDark: false,
    bg: "#fffbeb",
    sidebar: "#fffdf5",
    card: "#ffffff",
    text: "#1c1917",
    accent: "#d97706",
    border: "#fef3c7",
    subtext: "#92400e",
  },
  {
    id: "light-green",
    label: "그린",
    isDark: false,
    bg: "#f0fdf4",
    sidebar: "#f7fef9",
    card: "#ffffff",
    text: "#14532d",
    accent: "#16a34a",
    border: "#dcfce7",
    subtext: "#166534",
  },
  {
    id: "light-blue",
    label: "블루",
    isDark: false,
    bg: "#eff6ff",
    sidebar: "#f5f9ff",
    card: "#ffffff",
    text: "#1e3a5f",
    accent: "#2563eb",
    border: "#dbeafe",
    subtext: "#1e40af",
  },
  {
    id: "light-purple",
    label: "퍼플",
    isDark: false,
    bg: "#f5f0ff",
    sidebar: "#ffffff",
    card: "#ffffff",
    text: "#2d1b69",
    accent: "#7c3aed",
    border: "#ede9fe",
    subtext: "#5b21b6",
  },
]

export const DEFAULT_THEME_ID = "dark"

export function getTheme(id) {
  return THEMES.find(t => t.id === id) || THEMES[0]
}
